preload = /home/doji/Downloads/Wallpaper/3pbm95d9s9u71.jpg
wallpaper = DP-2,/home/doji/Downloads/Wallpaper/3pbm95d9s9u71.jpg
wallpaper = HDMI-A-1,/home/doji/Downloads/Wallpaper/3pbm95d9s9u71.jpg
splash = false
